{
  "hash": "77deb61c3f816ab235791333ece9bd16",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Job Market Research 2024\"\nsubtitle: \"Final Report\"\nauthor:\n  - name: Angelina McKim\n    affiliations:\n      - id: bu\n        name: Boston University\n        city: Boston\n        state: MA\n  - name: Devin Blanchard\n    affiliations:\n      - ref: bu\n  - name: Leo Liu\n    affiliations:\n      - ref: bu\ndate: \"2025-10-14\"\nformat:\n  docx:\n    toc: true\n    number-sections: true\nbibliography: references.bib\ncsl: csl/econometrica.csl\nexecute:\n  echo: false\n  warning: false\n  message: false\n---\n\n# Introduction & Research Rationale\n\nThe job market in 2024 is undergoing a major transformation with the rise of artificial intelligence and widespread acceptance of long-distance/remote work. This analysis will examine the following key topics to uncover the factors that influence salary trends:\n\n**The restructuring of compensation due to AI, inflation, and remote work.**\n\nThe traditional pay structure is being reshaped as companies adapt to automation, rising costs of living, and a distributed workforce. These forces are pushing employers to rethink how they reward skills, experience, and location.\n\n**Growing pay disparities across regions, industries, and job types in 2024.**\n  \nHigh-paying jobs are increasingly concentrated in specific tech-driven sectors and urban hubs. Meanwhile, many essential or service-based roles are seeing slower wage growth, deepening inequality across the workforce.\n\n**Shifting salary patterns based on remote flexibility, job type, and sector growth.**\n  \nRemote roles now often offer comparable or even higher compensation due to talent shortages and broader applicant pools. Industries like tech and healthcare are setting new standards, while others struggle to keep pace.\n\n# Literature Review Summary\n\nThe rise of Artificial Intelligence (AI) has reshaped the job market across the US, with demand for AI-related skills increasing dramatically. According to a study by PWC, jobs that require AI specialist skills are growing 3.5 times faster than all other job markets, with skilled AI workers being paid up to 25% more in some sectors [@pwc2024]. However, this increase in compensation is not limited to workers specialized in AI. Non-AI roles that require complementary skills such as digital literacy, analytical thinking, and teamwork are also seeing a 5–10% wage increase [@makela2024]. According to US job vacancy data from 2018–2024, AI-related jobs are significantly more likely to include non-monetary benefits as part of the compensation package, including parental leave and remote working options [@stephany2025].\n\nBeyond the benefit of not having to commute and the ability to work from anywhere, long-distance and remote roles are often sought after by job seekers due to faster wage growth. In a study comparing the pay trends of remote versus in-office workers in the same occupation, remote workers experienced 4.4% faster annual wage growth, especially in professional and technical sectors [@pabilonia2025]. Furthermore, workers who transitioned into remote roles with the same employer saw up to 16 percentage points higher wage growth than their counterparts who remained local [@romem2024]. This demonstrates that switching into remote work can lead to significantly higher wage growth, even within the same company and/or job category.\n\n# Methodology\nBelow are the steps we took to prepare the dataset to ensure accuracy and statistical integrity in our exploratory data analysis (EDA). \n\n## Remove Unnecessary Columns\nFirstly, columns containing redundant and irrelevant information were excluded from the dataset. Since the scope of this analysis is focused on job market trends in 2024, it is best practice to remove any outdated NAICS/SOC fields to prevent confusion and duplication. Similarly, metadata fields or duplicate fields that could introduce ambiguity and do not add any meaningful to downstream analysis are excluded. To summarize, unnecessary columns containing the following information were dropped:\n\n- Meta/tracking\n- Duplicated location info\n- Raw/duplicate title & body\n- Duplicated employment info\n- Education code columns\n- Redundant NAICS/SOC versions\n- LOT/V6 occupation hierarchy\n- ONET & CIP codes \n- Sectors\n\n## Handling of missing values \nWe addressed missing values based on field type and the amount of data missing per field: \n\n### Numerical Fields\nMissing values in key numerical fields were imputed with the median of each respective fields. Since these numerical fields are key for grouping and visualizing trends, simply removing empty rows could reduce the diversity of the dataset and introduce biases. The rationale for imputing the median rather than the mean is that the latter tends to be influenced by outliers and skewed distributions, which is often exhibited in fields like \"SALARY. Based on the downstream EDA, additional filtering may be applied to exclude imputed values altogether to prevent distorition and ensure statistical integrity in the trends observed. \n\n### Categorical Fields\nMissing values in key categorical fields were imputed with the placeholder value \"Unknown\" in order to prevent those rows of data being dropped, leading to unnecessary data loss. By imputing a neutral label like \"Unknown\", this strategy ensures that data integrity is retained without introducing false assumptions and biases into the downstream analysis. \n\n### Columns containing Majority Missing Data\nWhile the above addressed the rationale for imputing missing values, having to impute the majority of a column's values can also create noise, which provides insignificant information and analytical value to the downstream analysis. Therefore, columns containing more than 50% missing values were excluded from the dataset. \n\n![Figure 1: Non-null Data](figures/non-null_data.png)\n\n\n\n::: {.cell execution_count=2}\n\n::: {.cell-output .cell-output-stdout}\n```\n                         Column  Missing %\n           MAX_YEARS_EXPERIENCE  88.372093\n             MAX_EDULEVELS_NAME  77.495931\n                         SALARY  57.505035\n                      SALARY_TO  55.311871\n            ORIGINAL_PAY_PERIOD  55.311871\n                    SALARY_FROM  55.311871\n                       DURATION  37.678281\n           MIN_YEARS_EXPERIENCE  31.926398\n               MODELED_DURATION  26.607631\n                MODELED_EXPIRED  21.264035\n                        EXPIRED  10.819609\n                       MSA_NAME   5.447047\n                    COMPANY_RAW   0.746227\n                    TITLE_CLEAN   0.193109\n                     SOC_5_NAME   0.060691\n             SPECIALIZED_SKILLS   0.060691\n        SPECIALIZED_SKILLS_NAME   0.060691\n                 CERTIFICATIONS   0.060691\nLOT_SPECIALIZED_OCCUPATION_NAME   0.060691\n            CERTIFICATIONS_NAME   0.060691\n     LOT_SPECIALIZED_OCCUPATION   0.060691\n             COMMON_SKILLS_NAME   0.060691\n                    SKILLS_NAME   0.060691\n                SOFTWARE_SKILLS   0.060691\n           SOFTWARE_SKILLS_NAME   0.060691\n                  COMMON_SKILLS   0.060691\n              NAICS_2022_6_NAME   0.060691\n                         SKILLS   0.060691\n                          TITLE   0.060691\n                     STATE_NAME   0.060691\n                      CITY_NAME   0.060691\n               REMOTE_TYPE_NAME   0.060691\n                    REMOTE_TYPE   0.060691\n                  IS_INTERNSHIP   0.060691\n             MIN_EDULEVELS_NAME   0.060691\n            COMPANY_IS_STAFFING   0.060691\n                   COMPANY_NAME   0.060691\n                        COMPANY   0.060691\n                           BODY   0.060691\n                         POSTED   0.030346\n```\n:::\n:::\n\n\n## Remove Duplicates \nTo eliminate true duplicates from the dataset, job listings that have identical values in all the fields listed below were removed to prevent distortion and ensure statistical integrity: \n\n  - Job Title\n  - Company Name\n  - Location\n  - Posting Date\n  - Skill requirements\n  - Employment type\n\n<!-- ```{python}\n# ADDING IN MORE LIBRARIES\n# -------------------------------------------------------------------\n# Global Plotly Styling — applies to all visualizations in this report\n# -------------------------------------------------------------------\nimport plotly.io as pio\nimport plotly.graph_objects as go\nimport plotly.express as px\n\n# pio.templates.default = \"plotly_white\"\n# pio.templates[\"plotly_white\"].layout.font.family = \"Arial\"\n# pio.templates[\"plotly_white\"].layout.font.size = 14\n# pio.templates[\"plotly_white\"].layout.title.font.size = 18\n\ncustom_theme = go.layout.Template(\n    layout=go.Layout(\n        font=dict(family=\"Arial\", size=12, color=\"#000000\"),\n        title=dict(font=dict(size=16, family=\"Arial\", color=\"#000000\")),\n        paper_bgcolor=\"white\",\n        plot_bgcolor=\"white\",\n        colorway=px.colors.qualitative.Set2,\n        xaxis=dict(\n            showgrid=False,\n            gridcolor=\"#c0c0c0\",  # same as Matplotlib grid\n            zeroline=False,\n            linecolor=\"black\",\n            mirror=True,\n            ticks=\"outside\",\n            title_font=dict(size=13, family=\"Arial\"),\n            tickfont=dict(size=11, family=\"Arial\")\n        ),\n        yaxis=dict(\n            showgrid=True,\n            gridcolor=\"#c0c0c0\",\n            zeroline=False,\n            linecolor=\"black\",\n            mirror=True,\n            ticks=\"outside\",\n            title_font=dict(size=13, family=\"Arial\"),\n            tickfont=dict(size=11, family=\"Arial\")\n        )\n    )\n)\n\npio.templates[\"custom_white\"] = custom_theme\npio.templates.default = \"custom_white\"\n\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nplt.style.use(\"seaborn-v0_8-whitegrid\") \nplt.rcParams.update({\n    \"font.family\": \"Arial\",\n    \"font.size\": 7,\n    \"axes.titlesize\": 11,\n    \"axes.labelsize\": 9,\n    \"axes.edgecolor\": \"black\",\n    \"axes.linewidth\": 0.8,\n    \"figure.dpi\": 120,\n    \"savefig.dpi\": 150,\n    \"axes.grid\": True,\n    \"grid.color\": \"#c0c0c0\"\n})\nsns.set_palette(\"Set2\")\n``` -->\n\n\n\n# EDA Overview\nThis section explores job market trends and the restructuring of compensation through a series of visualizations. Each exploratory data analysis (EDA) was chosen to reveal specific patterns in compensation to highlight the impact of AI and remote work.\n\n\n\n\n\n## Salary by Remote Work Type\nThe purpose of this EDA is to visually compare not just the average pay, but also the range and consistency of salaries across different work arrangements. This visualization could reveal that remote roles have a wider salary range, indicating that companies are paying a premium for top talent regardless of location.\n\n\n\n![Figure 2: Salary Distribution by Work Arrangement](figures/salary_by_work_arrangement.png)\n\n**Key Insights:**\nThe median salaries across all work arrangements are similar, clustering around $115,000. However, both Remote and Hybrid Remote roles exhibit a much wider salary range and more high-paying outlier positions, with some remote roles exceeding $350,000. This suggests that while typical pay is comparable, remote-friendly positions offer significantly greater potential for top-end compensation.\n\n\n## Top Skills vs. Average Salary\nThe purpose of this EDA is to identify which specific skills are most financially valuable in the current job market, connecting AI-related skills to compensation. This could reveal that skills related to AI/ML platforms command a significantly higher salary, even if they aren't the most frequently requested skills overall.\n\n\n\n![Figure 3: Average Salary for Top 10 Skills most in Demand](figures/topskills_salary.png)\n\n**Key Insights:**\nAmong the 10 most in-demand skills, Data Analysis commands the highest average salary at over $120,000. While compensation for most top skills is competitive, technical skills like Data Analysis and Business Process show a slight financial advantage over the lowest-paid skill in this group, Management, which averages approximately $110,000.\n\n\n## Salary Trends by Top Industries\nThe purpose of this EDA is to explore how compensation varies across economic sectors and identify which industries offer the highest earning potential. Using the 2024 job posting data and grouping by industry (NAICS 2022 Level-6 codes), this analysis aims to compare the median salary and salary distribution across highest-paying industries within the job market. \n\n\n\n\n\n![Figure 4: Median Salary by Industry](figures/median_salary_by_industry.png)\n\n\n\n![Figure 5: Salary Distribution by Industry](figures/salary_distribution_by_industry.png)\n\n**Key Insights:**\nThe analysis of median salary across industries shows that Web Search Portals and All Other Information Services leads with the highest median pay, exceeding $160,000. This is likely due to the increasing demand on specialized digital infrastructure and AI-driven information services. The box plot shows a wide interquartile range (IQR), indicating a significant pay gap between entry-level and more senior/specialized roles in the industry. This trend is also observed in the Computing Infrastructure Providers, Data Processing, Web Hosting, and Related Services category, which is indicative of the range of roles in demand for those industries. Although other technology and information industries such as Software Publishers and Computer System Design Services reported slightly lower median salaries compared to the top-paying sectors, the large amount of high-end outlier values suggests that these industries still offer high-earning potential for more senior/specialized roles with most positions clustering around mid-range salaries. \n\nNotably, non-technology/information-related sectors such as All Other Miscellaneous Retailers also reported high median salaries, around $160,000. The broad definition of these sectors likely encompasses various types of retail firms that may include roles and platforms beyond the traditional frontline retail and sales roles. Another sector in which compensation data may be inflated by data categorization is Offices of Certified Public Accountants (CPAs), which reported a median salary of around $145,000. Based on the salary distribution highlighted in the box plot, the positively-skewed distribution indicates that while most CPA roles earn around the median, some specialized roles are earning substantially more. This aligns with how CPA firms are typically structured, where a small number of senior partners and high-level executives driving the high-end outliers. \n\nThese findings show that companies in technology, professional services, and consulting industries offer the highest median salaries and exhibit a larger dispersion in compensation, which is reflective of a more diverse workforce structure that may include entry level, technical/specialist, and senior leadership roles. On the other hand, administrative and support service sectors demonstrate lower median but tighter distributions in salary, demonstrating a more standardized workforce and wage structure in comparison. \n\n\n## AI vs. Non-AI Salary Comparison \nThe motivation for this analysis was to investigate how specialization in AI-related skills influence salary in today's job market. This analysis differentiates AI vs. non-AI jobs by identifying AI-related keywords such as machine learning, data science, computer vision, and natural language processing in job postings. We then compare the median and distribution of salaries between the two groups to determine whether AI roles command higher compensation than non-AI roles. \n\n::: {.cell execution_count=11}\n\n::: {.cell-output .cell-output-stdout}\n```\nis_ai_job\nNon-AI    15948\nAI         5273\nName: count, dtype: int64\n```\n:::\n:::\n\n\n\n\n![Figure 6: Salary Distribution comparison between AI vs. Non-AI Jobs](figures/AI_v_nonAI_salary_boxplot.png)\n\n\n\n![Figure 7: Salary Density comparison between AI vs. Non-AI Jobs](figures/AI_v_nonAI_salary_KDE.png)\n\n**Key Insights:**\nThe salary comparison between AI and non-AI job postings shows a wage premium associated with roles that require AI-related skill sets. Analyzing 5273 AI roles and 15949 non-AI roles, the box plot shows that AI roles have a higher median salary ($115,000-$120,000) than non-AI roles ($105,000-$110,000). In terms of IQRs - both Q1 and Q3 for AI roles is positioned higher in comparison to non-AI roles. This suggests that roles that require expertise in AI-related skills generally pay better than the rest of the job market. \n\nThe KDE plot shows that AI roles have a steep upward slope from $20,000-$80,000 with job postings mostly clustering between $80,000-$120,000. This pattern likely means that there are less entry-level roles in AI and most roles are concentrated in the mid-salary range. This suggests that while there aren’t many jobs that reflect entry level salaries, AI-related job postings reflect a higher salary floor driven by a higher barrier of entry. \n\n# Skill Gap Analysis\n\n## Internal Skills Assessment\nTo evaluate the current technical skill set for each team member, each team member performed a self-rating for a set of core competencies for data analytics and data science, which included Python, SQL, Power BI, Tableau, Excel, Machine Learning, Natural Language Processing (NLP), Cloud Computing, and AWS. The assessment was made on a five-point scale, and the rating values were then compiled into a dataframe for further analysis. We then leveraged a Seaborn heatmap to identify where our strengths concentrated and pinpoint where the gaps existed. \n\n\n\n\n\n\n\n![Figure 8: Team Skill Levels Heatmap](figures/Team_Skills_Heatmap.png)\n\n**Which skills should each member prioritize learning?**\n\n- **Angelina** – Strong in visualization tools (Power BI 5, Tableau 4, Excel 5). Next priorities: Cloud, AWS, Machine Learning, and NLP. These are high-demand in job postings (Cloud: 64k+, AWS: 10k+, ML/NLP combined: 23k+).  \n- **Devin** – Solid in Excel (5) and Tableau (5), but weakest in Python, ML, NLP, and AWS. Needs to raise Cloud as well.  \n- **Leo** – Stronger in Power BI (4) and Excel (4), but very low in ML, NLP, Cloud, and AWS. Should also build up Python and SQL to meet market demand (Python: 17k+, SQL: 43k+ mentions).  \n\n## External Skills Assessment using Natural Language Processing techniques\nTo identify the most in-demand skills in the analytics job market, we analyzed the job descriptions from the Lightcast dataset by leveraging Natural Language Processing (NLP) techniques to process the BODY column which contained detailed job descriptions. Below is a summary of the data preparation and extraction process:\n\n- **Text normalization:** To ensure consistency, job descriptions were converted to lowercase, Unicode-normalized format, and whitespaces were stripped. \n- **Tokenization:** Numbers and punctuation were filtered out to ensure words can be captured and extracted properly.\n- **Stopword removal:** To further filter and concentrate only on meaningful technical words, common English stopwords were removed using Scikit-learn's built-in stopword list. \n- **Keyword filtering:** A predefined list of relevant analytics skills (e.g., Python, SQL, AWS, Tableau, Excel, Pandas, Spark, Machine Learning, NLP, Cloud Computing) was used to identify and count occurrences within the job descriptions.\n- **Frequency analysis:** Using Python's Counter() function, we tallied the frequency of each skill keyword and visualized in a column chart to understand their significance in the job market. \n\n::: {.cell execution_count=17}\n\n::: {.cell-output .cell-output-stdout}\n```\nScanning job descriptions and counting tokens (streaming)...\nTop data analytics skills from job descriptions\ncloud:42787\nsql:35871\npower:21894\nexcel:19874\nlearning:16361\ntableau:14609\npython:13402\naws:8510\nmachine:5592\ncomputing:2588\nspark:1496\ndocker:613\npandas:378\nnlp:293\nnumpy:187\n```\n:::\n:::\n\n\n![Figure 9: Most In-demand skills from Job Descriptions](figures/jd_top_skills.png)\n\n## Propose an Improvement Plan\nAccording to our analysis, job postings show high demand for Cloud, SQL, Python, ML, and AWS. Our team is strong in visualization (Excel, Power BI, Tableau) but weaker in Cloud, ML, and NLP. This plan aligns our learning with market needs, provides specific resources, and ensures collaboration strategies so the whole team can close the gap together.\n\n**What courses or resources can help?**\n\n- **Cloud & AWS** – free cloud provider tutorials, AWS Educate, and cloud labs for hands-on practice.  \n- **Machine Learning & NLP** – scikit-learn tutorials, Kaggle competitions, and university modules on ML/NLP.  \n- **Python & SQL** – interactive platforms (Jupyter notebooks, LeetCode SQL), and official documentation.  \n- **Docker & Spark** – short online workshops, Spark quickstarts, and Docker “getting started” labs.  \n\n\n**How can the team collaborate to bridge skill gaps?**\n\n- **Role rotation:** assign rotating leads (“cloud lead,” “ML/NLP lead,” “Python/SQL lead”) for mini-projects so each teammate practices outside their strengths.  \n- **Lightning talks:** weekly 15-minute sessions where one teammate teaches a concept or tool they just learned.  \n- **Pair programming:** match stronger members (for example, Angelina for visualization) with weaker ones (for example, Devin on Python) to share knowledge in real time.  \n- **Shared resources:** maintain a team wiki with reusable queries, cloud setup notes, and code snippets.  \n\n\n\n\n# Regression, Classification, and Topic Insights\n\n## KMeans Clustering Analysis\nWe performed KMeans clustering on job postings using core features (salary, minimum and maximum years of experience). This analysis seeks to segment jobs into groups with similar compensation and experience profiles, and to interpret these clusters using industry categories (NAICS).\n\n### Fit KMeans and Assign Clusters - Data Prep\nWe used KMeans clustering to segment jobs into five groups, using standardized salary and experience as inputs. Each posting is assigned to a cluster.\n\n![Figure 10: KMeans Clusters by Salary and Min Years Experience](figures/KMeans_Cluster.png)\n\n\n\n\n\n::: {.cell execution_count=20}\n\n::: {.cell-output .cell-output-stdout}\n```\nKMeans labels column ready: True\nUnique clusters: 5\nTop 5 Job Titles for Each Cluster:\n\n\nCluster 0:\nTITLE_CLEAN\ndata analyst                     393\nsenior data analyst               94\nbusiness intelligence analyst     88\nsr data analyst                   37\ndata analyst iii                  26\nName: count, dtype: int64\n\nCluster 1:\nTITLE_CLEAN\ndata analyst            81\nenterprise architect    54\nsenior data analyst     23\nsolution architect      18\ndata modeler            17\nName: count, dtype: int64\n\nCluster 2:\nTITLE_CLEAN\ndata analyst                     681\nbusiness intelligence analyst    106\ndata analyst ii                   42\nsenior data analyst               35\nresearch data analyst             26\nName: count, dtype: int64\n\nCluster 3:\nTITLE_CLEAN\ndata analyst                                              68\nenterprise architect                                      59\nsenior data analyst                                       44\ndata engineer analytics                                   30\noracle cloud supply chain management senior consultant    19\nName: count, dtype: int64\n\nCluster 4:\nTITLE_CLEAN\nenterprise architect                            56\nsolution architect                              18\noracle cloud supply chain management manager    14\nprincipal enterprise architect                  14\nenterprise platform architect                   12\nName: count, dtype: int64\n```\n:::\n:::\n\n\n### K-Means Clustering Summary\nClustering on salary and minimum experience produced three clear market segments:\n\n- Entry-level / lower salary\n- Mid-career / moderate salary\n- Senior specialist / high salary\n\nThis segmentation aligns with career ladders and confirms the broad, positive relationship between experience and compensation.\n\n**Business relevance**\n\n- **Job seekers**: Use cluster patterns to target industries/roles occupying higher-pay segments and to plan upskilling.\n- **Employers**: Map openings to cluster ranges to calibrate pay bands against the external market and reduce attrition risk.\n\n<!-- ```{python}\n# --- Bar chart for the top 5 titles in Cluster 0 (change cluster_num as needed) ---\ncluster_num = 0\ntop_titles = df[df['KMEANS_CLUSTER'] == cluster_num]['TITLE_CLEAN'].value_counts().head(5)\n\nplt.figure(figsize=(8, 5))\nbars = top_titles.plot(kind='bar', color='skyblue')\nplt.title(f'Top 5 Job Titles in Cluster {cluster_num}')\nplt.xlabel('Job Title')\nplt.ylabel('Count')\nplt.xticks(rotation=45, ha='right') \nout_path = \"figures/Top_5_Job_Titles_in_Cluster.png\"\nplt.savefig(out_path, dpi=150, bbox_inches=\"tight\")\n\n# Add the counts on top of the bars\nfor idx, value in enumerate(top_titles.values):\n    plt.text(idx, value + max(top_titles.values)*0.01, str(value), ha='center', va='bottom', fontweight='bold')\n\nplt.tight_layout()\n#plt.show()\nplt.close()\n#![Top 5 Job Titles in Cluster 0](figures/Top_5_Job_Titles_in_Cluster.png)\n``` -->\n\n\n\n## Regression – Predicting Salary\nWe chose Random Forest over Linear Regression because the relationship between experience and salary is non-linear, and the model captures complex interactions more effectively.\n\nThe goal of this model is to predict job posting salary using experience and employment type features. The model uses an 80/20 train–test split and evaluates performance using RMSE and R² metrics.\n\n\n\n::: {.cell execution_count=23}\n\n::: {.cell-output .cell-output-stdout}\n```\nRoot Mean Squared Error (RMSE): 34744.38\nR² Score: 0.336\n```\n:::\n:::\n\n\n### Regression Results and Interpretation\nWe modeled salary using Minimum Years of Experience (MIN_YEARS_EXPERIENCE) and Remote Type (REMOTE_TYPE_NAME). We excluded MAX_YEARS_EXPERIENCE (>85% missing) to protect statistical integrity; this reduced sample size but improved reliability.\n\n**Model performance**\n\n- **RMSE**: 34,744.38\n- **R²**: 0.336\n\n**What this means**\nAn R² of 0.336 indicates experience and remote status explain a meaningful, but incomplete share of salary variation. That’s consistent with cross-industry labor data, where compensation is also driven by occupation, industry, location, and scarce technical capabilities.\n\n**Business relevance**\n\n- **For job seekers**: Experience contributes to higher earnings, but targeted specialization (e.g., analytics, cloud, data engineering) and industry selection are decisive for larger pay jumps.\n- **For employers**: Pricing talent solely by tenure can misalign offers in high-skill roles. Clear remote/on-site definitions in postings improve candidate signal and reduce noise in market benchmarking.\n\n\n\n![Predicted vs. Actual Salary (Random Forest Regression)](figures/Predicted_vs_Actual_RF_Regression.png)\n\n::: {.cell execution_count=25}\n\n::: {.cell-output .cell-output-stdout}\n```\nTop 5 features influencing salary prediction:\nMIN_YEARS_EXPERIENCE: 0.953\nREMOTE_TYPE_NAME_Not Remote: 0.017\nREMOTE_TYPE_NAME_[None]: 0.015\nREMOTE_TYPE_NAME_Remote: 0.014\nREMOTE_TYPE_NAME_Unknown: 0.000\n```\n:::\n:::\n\n\n\n\n![Top 5 Feature Importances (Random Forest Regression)](figures/Top_5_Feature_Importances_RF_Regression.png)\n\n::: {.cell execution_count=27}\n\n::: {.cell-output .cell-output-stdout}\n```\n         SALARY  MIN_YEARS_EXPERIENCE REMOTE_TYPE_NAME\n10189  312500.0                   1.0           [None]\n19209  312000.0                   1.0           [None]\n31552  328600.0                   5.0           [None]\n2258   305000.0                   3.0           [None]\n29554  338750.0                   7.0           [None]\n```\n:::\n:::\n\n\n\n\n### Outlier Jobs and Market Signals\nThe largest residuals include postings above $300,000 with only 1–5 years minimum experience, often missing a remote/on-site label. These cases point to specialized, high-impact roles where compensation is decoupled from tenure (e.g., advanced analytics, cloud/platform, niche leadership).\n\nA small number of postings show very high pay at low experience with unspecified remote type. These likely reflect specialized roles or incomplete records. In practice, validate or isolate these cases before setting salary bands or training production models.\n\n![Top 5 Outlier Job Salaries](figures/Top_5_Outlier_Job_Salaries.png)\n\n**Business relevance**\n\n- **Employers**: Standardize and QA high-pay, low-tenure postings, unclear fields and atypical mixes should be reviewed before publication.\n- **Job seekers**: Outliers highlight skill paths where focused upskilling can command premium pay earlier in a career.\n\n## Classification – Predicting Remote vs On-Site Job\nWe trained a logistic regression to predict Remote vs On-Site using MIN_YEARS_EXPERIENCE plus an available categorical descriptor (e.g., employment type or state).\n\n::: {.cell execution_count=29}\n\n::: {.cell-output .cell-output-stdout}\n```\nAccuracy: 0.619, F1 Score: 0.328\n```\n:::\n:::\n\n\n![Confusion Matrix — Remote vs On-Site Classification](figures/Confusion_Matrix_Remote_vs_On-Site.png)\n\n### Classification Results and Interpretation\n**Performance:**\n\n- **Accuracy**: 0.622\n- **F1 Score**: 0.327\n\n**What this means:**\nThe model distinguishes remote vs. on-site at a moderate level, consistent with the idea that remote status is policy/role-design driven, not primarily a function of required experience.\n\n**Business relevance:**\n\n- **Employers:** Remote flexibility can be offered across experience levels without materially distorting supply. If remote status is strategic, emphasize role/industry signals rather than tenure in postings.\n- **Job seekers:** Remote options exist from entry to senior levels, broadening geographic reach and negotiation leverage.\n\n# Conclusion & Recommendation\nThis project, which analyzed the 2024 job market, provided key insights into the factors influencing compensation and future workforce development. Our analysis confirms that the employment landscape is being fundamentally reshaped by technology and the demand for flexible work, creating both challenges and opportunities for job seekers and employers.\n\n## Key Findings and Market Dynamics\nSkill-Driven Wage Premiums\nOur Natural Language Processing (NLP) analysis identified a clear difference between the team’s strengths and current market demand. While the team performs well in visualization tools such as Excel, Power BI, and Tableau, the job market places greater emphasis on Cloud Computing, SQL, Python, and Machine Learning (ML). The frequency of these skills in job postings shows that focused development in these areas supports higher compensation and continued competitiveness in analytics roles.\nExperience as the Primary Salary Driver\nThe Random Forest Regression model achieved an RMSE of 34,744.38 and an R² of 0.336, identifying Minimum Years of Experience as the most influential feature in predicting salary, with a feature importance of approximately 0.953. This result indicates that, while technical specialization enhances access to well-paid roles, accumulated experience continues to be the main factor influencing salary progression.\nThe Segmented Job Market\nThe KMeans Clustering model grouped job postings into five clusters, summarized into three main tiers—Entry-Level (lower salary), Mid-Career (moderate salary), and Senior Specialist (higher salary). This pattern aligns with traditional career development paths and suggests that job seekers should aim for higher-tier roles by combining experience with proficiency in high-demand skills such as Cloud Computing, Python, and Machine Learning.\nRemote Work Status is Not Experience-Dependent\nThe Logistic Regression model achieved an accuracy of 0.622 and an F1 score of 0.327, showing moderate predictive strength when using experience to classify remote versus on-site jobs. This suggests that remote flexibility depends more on company policy or role design than on years of experience. Remote opportunities appear across all experience tiers, providing both entry-level and senior professionals with broader access to roles.\n\n## Strategic Recommendations\nBased on these findings, the following strategies are recommended for both job seekers (the team) and employers:\nContinue Upskilling in Cloud and Machine Learning\nEfforts should focus on further developing Cloud/AWS and Machine Learning/NLP skills. These areas show the greatest opportunity for alignment with market needs and can improve access to higher-tier roles.\nStandardize High-Value Job Postings\nEmployers should review and standardize postings with high salaries and lower experience requirements. Accurate labeling of REMOTE_TYPE and clear definitions of required technical skills will improve market consistency, strengthen salary benchmarking, and attract well-matched candidates.\nUse Remote Flexibility to Expand Talent Pools\nSince remote status does not strongly depend on experience, employers can apply flexible work policies to reach qualified candidates at all career levels. This approach supports broader hiring while maintaining consistency in pay structures.\n\n",
    "supporting": [
      "final_report_files"
    ],
    "filters": []
  }
}